version: "3.8"

services:
  backend:
    build:
      context: ./Backend
    ports:
      - "8080:8080"
    environment:
      - DB_HOST=db
      - DB_PORT=3306
      - DB_USER=hirepilot
      - DB_PASSWORD=hirepilotpass
      - DB_NAME=hirepilot
    depends_on:
      - db

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "5173:80"
    depends_on:
      - backend

  db:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_DATABASE: hirepilot
      MYSQL_USER: hirepilot
      MYSQL_PASSWORD: hirepilotpass
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data: