version: '3.8'

services:
  nats:
    image: nats:latest
    command: ["-c", "/etc/nats/nats-server.conf"]
    ports:
      - "4222:4222"
      - "8222:8222"
      - "6222:6222"
    volumes:
      - nats.conf:/etc/nats/nats-server.conf
      - nats-data:/data
volumes:
  nats-data: