FROM golang:1.24 AS builder

WORKDIR /app

COPY linkedinscraper.go ./
COPY db.go ./
COPY nats.go ./
COPY .env ./

RUN go mod init linkedinscraper || true
RUN go mod tidy
RUN go build -o linkedinscraper ./linkedinscraper.go ./db.go ./nats.go

FROM gcr.io/distroless/base
COPY --from=builder /app/linkedinscraper /linkedinscraper
CMD ["/linkedinscraper"]