FROM golang:1.24 AS builder

WORKDIR /app

COPY consumer.go ./
COPY cvgenerator_main.go ./
COPY cv_utils.go ./
COPY db.go ./

RUN go mod init consumer || true
RUN go mod tidy
RUN go build -o consumer ./cvgenerator_main.go ./consumer.go ./cv_utils.go ./db.go

FROM gcr.io/distroless/base
COPY --from=builder /app/consumer /consumer
CMD ["/consumer"] 