FROM golang:1.24 AS builder

WORKDIR /app

# Copy shared library first
COPY shared ./shared

# Copy CoverGenerator files
COPY CoverGenerator ./CoverGenerator

# Set working directory to CoverGenerator
WORKDIR /app/CoverGenerator

RUN go mod tidy && go build -o covergenerator .

FROM gcr.io/distroless/base

COPY --from=builder /app/CoverGenerator/covergenerator /covergenerator

CMD ["/covergenerator"]