FROM golang:1.24 AS builder

WORKDIR /app

# Copy shared library first
COPY shared ./shared

# Copy JobService files
COPY PromptService ./PromptService

# Set working directory to JobService
WORKDIR /app/PromptService

RUN go mod tidy && go build -o promptservice .

FROM gcr.io/distroless/base

COPY --from=builder /app/PromptService/promptservice /promptservice

CMD ["/promptservice"]