FROM golang:1.24 AS builder

WORKDIR /app

# Copy shared library first
COPY shared ./shared

# Copy ScoreGenerator files
COPY ScoreGenerator ./ScoreGenerator

# Set working directory to ScoreGenerator
WORKDIR /app/ScoreGenerator

RUN go mod tidy && go build -o scoregenerator .

FROM gcr.io/distroless/base

COPY --from=builder /app/ScoreGenerator/scoregenerator /scoregenerator

CMD ["/scoregenerator"] 