FROM golang:1.24 AS builder

WORKDIR /app

# Copy shared library first
COPY shared ./shared

# Copy JobService files
COPY JobService ./JobService

# Set working directory to JobService
WORKDIR /app/JobService

RUN go mod tidy && go build -o jobservice .

FROM gcr.io/distroless/base

COPY --from=builder /app/JobService/jobservice /jobservice

CMD ["/jobservice"]